[patch.crates-io]
kutil = { path = "../kutil/library" }
kutil-std-macros = { path = "../kutil/std-macros" }
depiction = { path = "../depiction/library" }
depiction-macros = { path = "../depiction/macros" }
